name: "Setup MSSQL"
branding:
  icon: "database"
  color: "yellow"
description: "Installs an MSSQL server and client"
inputs:
  components:
    description: "The components to install"
    required: true
  sa-password:
    description: "The SA password for the SQL instance"
    required: true
  version:
    description: "The version of the SQL instance"
    required: true
runs:
  using: "composite"
  steps:
    - shell: pwsh
      run: |
        $params = @{
            Components = ("${{ inputs.components }}" -split ",").Trim()
            SaPassword = "${{ inputs.sa-password }}"
            Version = "${{ inputs.version }}"
        }

        ${{ github.action_path }}/install.ps1 @params
      env:
        HOMEBREW_NO_AUTO_UPDATE: "1"
